# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 650))
        MainWindow.setMaximumSize(QtCore.QSize(700, 650))

        # centers the interface on startup
        qt_rectangle = MainWindow.frameGeometry()
        center_point = QtWidgets.QDesktopWidget().availableGeometry().center()
        qt_rectangle.moveCenter(center_point)
        MainWindow.move(qt_rectangle.topLeft())

        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.group_box_options = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_options.setGeometry(QtCore.QRect(20, 130, 661, 341))
        self.group_box_options.setObjectName("group_box_options")
        self.label = QtWidgets.QLabel(self.group_box_options)
        self.label.setGeometry(QtCore.QRect(20, 280, 641, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.group_box_options)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 300, 351, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_13.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radio_threads_no = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_threads_no.sizePolicy().hasHeightForWidth())
        self.radio_threads_no.setSizePolicy(sizePolicy)
        self.radio_threads_no.setObjectName("radio_threads_no")
        self.horizontalLayout_13.addWidget(self.radio_threads_no)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_threads_yes = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_threads_yes.sizePolicy().hasHeightForWidth())
        self.radio_threads_yes.setSizePolicy(sizePolicy)
        self.radio_threads_yes.setChecked(True)
        self.radio_threads_yes.setObjectName("radio_threads_yes")
        self.horizontalLayout_2.addWidget(self.radio_threads_yes)
        self.txt_nb_cores = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nb_cores.sizePolicy().hasHeightForWidth())
        self.txt_nb_cores.setSizePolicy(sizePolicy)
        self.txt_nb_cores.setMinimumSize(QtCore.QSize(50, 0))
        self.txt_nb_cores.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_nb_cores.setObjectName("txt_nb_cores")
        self.horizontalLayout_2.addWidget(self.txt_nb_cores)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.group_box_options)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 247, 123, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.txt_char = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_char.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_char.sizePolicy().hasHeightForWidth())
        self.txt_char.setSizePolicy(sizePolicy)
        self.txt_char.setMaximumSize(QtCore.QSize(20, 16777215))
        self.txt_char.setObjectName("txt_char")
        self.horizontalLayout.addWidget(self.txt_char)
        self.layoutWidget2 = QtWidgets.QWidget(self.group_box_options)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 100, 381, 28))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_19.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_19.addWidget(self.label_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.check_separate_yes = QtWidgets.QRadioButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_separate_yes.sizePolicy().hasHeightForWidth())
        self.check_separate_yes.setSizePolicy(sizePolicy)
        self.check_separate_yes.setChecked(True)
        self.check_separate_yes.setObjectName("check_separate_yes")
        self.horizontalLayout_14.addWidget(self.check_separate_yes)
        self.check_separate_no = QtWidgets.QRadioButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_separate_no.sizePolicy().hasHeightForWidth())
        self.check_separate_no.setSizePolicy(sizePolicy)
        self.check_separate_no.setObjectName("check_separate_no")
        self.horizontalLayout_14.addWidget(self.check_separate_no)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_14)
        self.layoutWidget3 = QtWidgets.QWidget(self.group_box_options)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 232, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_21.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_21.addWidget(self.label_7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.radio_english = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radio_english.setChecked(True)
        self.radio_english.setObjectName("radio_english")
        self.horizontalLayout_20.addWidget(self.radio_english)
        self.radio_original = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radio_original.setObjectName("radio_original")
        self.horizontalLayout_20.addWidget(self.radio_original)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_20)
        self.layoutWidget4 = QtWidgets.QWidget(self.group_box_options)
        self.layoutWidget4.setGeometry(QtCore.QRect(21, 61, 625, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_17.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_17.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radio_concatenate_all = QtWidgets.QRadioButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_concatenate_all.sizePolicy().hasHeightForWidth())
        self.radio_concatenate_all.setSizePolicy(sizePolicy)
        self.radio_concatenate_all.setChecked(True)
        self.radio_concatenate_all.setAutoExclusive(True)
        self.radio_concatenate_all.setObjectName("radio_concatenate_all")
        self.horizontalLayout_16.addWidget(self.radio_concatenate_all)
        self.radio_concatenate_items = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radio_concatenate_items.setAutoExclusive(True)
        self.radio_concatenate_items.setObjectName("radio_concatenate_items")
        self.horizontalLayout_16.addWidget(self.radio_concatenate_items)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_16)
        self.checkBox_title = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_title.setEnabled(False)
        self.checkBox_title.setChecked(True)
        self.checkBox_title.setObjectName("checkBox_title")
        self.horizontalLayout_3.addWidget(self.checkBox_title)
        self.checkBox_abstract = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_abstract.setEnabled(False)
        self.checkBox_abstract.setChecked(True)
        self.checkBox_abstract.setObjectName("checkBox_abstract")
        self.horizontalLayout_3.addWidget(self.checkBox_abstract)
        self.checkBox_description = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_description.setEnabled(False)
        self.checkBox_description.setChecked(True)
        self.checkBox_description.setObjectName("checkBox_description")
        self.horizontalLayout_3.addWidget(self.checkBox_description)
        self.checkBox_claims = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_claims.setEnabled(False)
        self.checkBox_claims.setChecked(True)
        self.checkBox_claims.setObjectName("checkBox_claims")
        self.horizontalLayout_3.addWidget(self.checkBox_claims)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.layoutWidget5 = QtWidgets.QWidget(self.group_box_options)
        self.layoutWidget5.setGeometry(QtCore.QRect(22, 130, 241, 28))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.radio_scrape_all = QtWidgets.QRadioButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_scrape_all.sizePolicy().hasHeightForWidth())
        self.radio_scrape_all.setSizePolicy(sizePolicy)
        self.radio_scrape_all.setChecked(True)
        self.radio_scrape_all.setAutoExclusive(True)
        self.radio_scrape_all.setObjectName("radio_scrape_all")
        self.horizontalLayout_18.addWidget(self.radio_scrape_all)
        self.radio_scrape_specific = QtWidgets.QRadioButton(self.layoutWidget5)
        self.radio_scrape_specific.setAutoExclusive(True)
        self.radio_scrape_specific.setObjectName("radio_scrape_specific")
        self.horizontalLayout_18.addWidget(self.radio_scrape_specific)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_18)
        self.widget = QtWidgets.QWidget(self.group_box_options)
        self.widget.setGeometry(QtCore.QRect(0, 170, 651, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(18, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_scrape_cited = QtWidgets.QCheckBox(self.widget)
        self.check_scrape_cited.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_scrape_cited.sizePolicy().hasHeightForWidth())
        self.check_scrape_cited.setSizePolicy(sizePolicy)
        self.check_scrape_cited.setCheckable(True)
        self.check_scrape_cited.setChecked(True)
        self.check_scrape_cited.setObjectName("check_scrape_cited")
        self.verticalLayout.addWidget(self.check_scrape_cited)
        self.check_scrape_classifications = QtWidgets.QCheckBox(self.widget)
        self.check_scrape_classifications.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_scrape_classifications.sizePolicy().hasHeightForWidth())
        self.check_scrape_classifications.setSizePolicy(sizePolicy)
        self.check_scrape_classifications.setMinimumSize(QtCore.QSize(0, 0))
        self.check_scrape_classifications.setCheckable(True)
        self.check_scrape_classifications.setChecked(True)
        self.check_scrape_classifications.setObjectName("check_scrape_classifications")
        self.verticalLayout.addWidget(self.check_scrape_classifications)
        self.check_PDF = QtWidgets.QCheckBox(self.widget)
        self.check_PDF.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_PDF.sizePolicy().hasHeightForWidth())
        self.check_PDF.setSizePolicy(sizePolicy)
        self.check_PDF.setChecked(True)
        self.check_PDF.setObjectName("check_PDF")
        self.verticalLayout.addWidget(self.check_PDF)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(18, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_scrape_citations = QtWidgets.QCheckBox(self.widget)
        self.check_scrape_citations.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_scrape_citations.sizePolicy().hasHeightForWidth())
        self.check_scrape_citations.setSizePolicy(sizePolicy)
        self.check_scrape_citations.setCheckable(True)
        self.check_scrape_citations.setChecked(True)
        self.check_scrape_citations.setObjectName("check_scrape_citations")
        self.verticalLayout_2.addWidget(self.check_scrape_citations)
        self.check_scrape_similar = QtWidgets.QCheckBox(self.widget)
        self.check_scrape_similar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_scrape_similar.sizePolicy().hasHeightForWidth())
        self.check_scrape_similar.setSizePolicy(sizePolicy)
        self.check_scrape_similar.setCheckable(True)
        self.check_scrape_similar.setChecked(True)
        self.check_scrape_similar.setObjectName("check_scrape_similar")
        self.verticalLayout_2.addWidget(self.check_scrape_similar)
        self.check_figures = QtWidgets.QCheckBox(self.widget)
        self.check_figures.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_figures.sizePolicy().hasHeightForWidth())
        self.check_figures.setSizePolicy(sizePolicy)
        self.check_figures.setChecked(True)
        self.check_figures.setObjectName("check_figures")
        self.verticalLayout_2.addWidget(self.check_figures)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(18, 68, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.check_scrape_nonpatent = QtWidgets.QCheckBox(self.widget)
        self.check_scrape_nonpatent.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_scrape_nonpatent.sizePolicy().hasHeightForWidth())
        self.check_scrape_nonpatent.setSizePolicy(sizePolicy)
        self.check_scrape_nonpatent.setCheckable(True)
        self.check_scrape_nonpatent.setChecked(True)
        self.check_scrape_nonpatent.setObjectName("check_scrape_nonpatent")
        self.verticalLayout_3.addWidget(self.check_scrape_nonpatent)
        self.check_scrape_legal = QtWidgets.QCheckBox(self.widget)
        self.check_scrape_legal.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_scrape_legal.sizePolicy().hasHeightForWidth())
        self.check_scrape_legal.setSizePolicy(sizePolicy)
        self.check_scrape_legal.setCheckable(True)
        self.check_scrape_legal.setChecked(True)
        self.check_scrape_legal.setObjectName("check_scrape_legal")
        self.verticalLayout_3.addWidget(self.check_scrape_legal)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(18, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.group_box_file = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_file.setGeometry(QtCore.QRect(20, 10, 661, 111))
        self.group_box_file.setObjectName("group_box_file")
        self.layoutWidget6 = QtWidgets.QWidget(self.group_box_file)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 69, 621, 32))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_10.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_save_directory = QtWidgets.QLabel(self.layoutWidget6)
        self.label_save_directory.setObjectName("label_save_directory")
        self.horizontalLayout_10.addWidget(self.label_save_directory)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.directoryPath = QtWidgets.QLineEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directoryPath.sizePolicy().hasHeightForWidth())
        self.directoryPath.setSizePolicy(sizePolicy)
        self.directoryPath.setObjectName("directoryPath")
        self.horizontalLayout_9.addWidget(self.directoryPath)
        self.SelectDirectory = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectDirectory.sizePolicy().hasHeightForWidth())
        self.SelectDirectory.setSizePolicy(sizePolicy)
        self.SelectDirectory.setObjectName("SelectDirectory")
        self.horizontalLayout_9.addWidget(self.SelectDirectory)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.layoutWidget7 = QtWidgets.QWidget(self.group_box_file)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 32, 631, 30))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_filename = QtWidgets.QLabel(self.layoutWidget7)
        self.label_filename.setAccessibleDescription("")
        self.label_filename.setObjectName("label_filename")
        self.horizontalLayout_11.addWidget(self.label_filename)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.filePath = QtWidgets.QLineEdit(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePath.sizePolicy().hasHeightForWidth())
        self.filePath.setSizePolicy(sizePolicy)
        self.filePath.setObjectName("filePath")
        self.horizontalLayout_8.addWidget(self.filePath)
        self.SelectFile = QtWidgets.QPushButton(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectFile.sizePolicy().hasHeightForWidth())
        self.SelectFile.setSizePolicy(sizePolicy)
        self.SelectFile.setObjectName("SelectFile")
        self.horizontalLayout_8.addWidget(self.SelectFile)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 460, 661, 161))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(20, 60, 621, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 30, 661, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(11, 1, 11, 1)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.label_status = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_6.addWidget(self.label_status)
        spacerItem7 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 100, 661, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(11, 1, 11, 1)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.startButton = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(200, 0))
        self.startButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_7.addWidget(self.startButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setShortcut('Ctrl+O')
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSelect_Directory = QtWidgets.QAction(MainWindow)
        self.actionSelect_Directory.setShortcut('Ctrl+S')
        self.actionSelect_Directory.setObjectName("actionSelect_Direcory")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSelect_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scraper"))
        self.group_box_options.setTitle(_translate("MainWindow", "Options"))
        self.label.setText(_translate("MainWindow", "Use multiple processing cores for faster scraping (recommended) :"))
        self.radio_threads_no.setText(_translate("MainWindow", "No"))
        self.radio_threads_yes.setText(_translate("MainWindow", "Yes (set the number or leave auto) :"))
        self.txt_nb_cores.setText(_translate("MainWindow", "auto"))
        self.label_5.setText(_translate("MainWindow", "CSV delimiter :"))
        self.txt_char.setText(_translate("MainWindow", ","))
        self.label_6.setText(_translate("MainWindow", "Abstract, Description and Claims folders "))
        self.check_separate_yes.setText(_translate("MainWindow", "Yes"))
        self.check_separate_no.setText(_translate("MainWindow", "No"))
        self.label_7.setText(_translate("MainWindow", "Language :"))
        self.radio_english.setText(_translate("MainWindow", "English"))
        self.radio_original.setText(_translate("MainWindow", "Original"))
        self.label_3.setText(_translate("MainWindow", "Concatenate :  "))
        self.radio_concatenate_all.setText(_translate("MainWindow", "All"))
        self.radio_concatenate_items.setText(_translate("MainWindow", "Selected items :"))
        self.checkBox_title.setText(_translate("MainWindow", "Title"))
        self.checkBox_abstract.setText(_translate("MainWindow", "Abstract"))
        self.checkBox_description.setText(_translate("MainWindow", "Description"))
        self.checkBox_claims.setText(_translate("MainWindow", "Claims"))
        self.label_4.setText(_translate("MainWindow", "Scrape  :"))
        self.radio_scrape_all.setText(_translate("MainWindow", "All"))
        self.radio_scrape_specific.setText(_translate("MainWindow", "Selected items :"))
        self.check_scrape_cited.setText(_translate("MainWindow", "Cited by"))
        self.check_scrape_classifications.setText(_translate("MainWindow", "Classifications"))
        self.check_PDF.setText(_translate("MainWindow", "PDF"))
        self.check_scrape_citations.setText(_translate("MainWindow", "Patent citations"))
        self.check_scrape_similar.setText(_translate("MainWindow", "Similar documents"))
        self.check_figures.setText(_translate("MainWindow", "Figures"))
        self.check_scrape_nonpatent.setText(_translate("MainWindow", "Non patent citations"))
        self.check_scrape_legal.setText(_translate("MainWindow", "Legal events"))
        self.group_box_file.setTitle(_translate("MainWindow", "Folders"))
        self.label_save_directory.setText(_translate("MainWindow", "Backup folder :"))
        self.SelectDirectory.setText(_translate("MainWindow", "Open"))
        self.label_filename.setText(_translate("MainWindow", "Patent list (CSV) :"))
        self.SelectFile.setText(_translate("MainWindow", "Open"))
        self.label_2.setText(_translate("MainWindow", "Status :"))
        self.label_status.setText(_translate("MainWindow", "Waiting..."))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSelect_Directory.setText(_translate("MainWindow", "Select Saving Directory"))
